//
// Created by emurray2 on 12/13/2019.
//

#ifndef INC_220GROUPPROJ_COLLECTIONLINKEDNODE2_H
#define INC_220GROUPPROJ_COLLECTIONLINKEDNODE2_H


class CollectionLinkedNode2 {

};


#endif //INC_220GROUPPROJ_COLLECTIONLINKEDNODE2_H
